blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/TEPPP-software/TEPPP/issues/new?template=bug_report.md&labels=bug+%3Abug%3A
    about: Report a bug
  - name: Documentation Issue
    url: https://github.com/TEPPP-software/TEPPP/issues/new?template=documentation_issue.md&labels=documentation+%3Abook%3A
    about: Report a documentation issue